"""Builds the Grafana dashboards in monitoring/grafana/dashboards/.

The JSON files there are generated by this script and are not edited by
hand: a filter, colour or query shared by many panels is defined once here.
To change a dashboard, edit this file and run it (no dependencies beyond
Python 3):

    python3 monitoring/grafana/build_dashboards.py

Grafana picks the new JSON up within 30 seconds. A panel tried out in the
UI has to be ported back into this script, or the next run overwrites it.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "dashboards"
PROM = {"type": "prometheus", "uid": "prometheus"}
PG = {"type": "grafana-postgresql-datasource", "uid": "tigerduck-db"}
LOKI = {"type": "loki", "uid": "loki"}
DB = 'datname="tigerduck"'

# ----------------------------------------------------------------- colours
GREEN, RED, ORANGE, YELLOW, BLUE, GRAY, PURPLE = (
    "green", "red", "orange", "yellow", "blue", "#8e8e8e", "purple")
STATUS_COLORS = {
    # good
    "sent": GREEN, "succeeded": GREEN, "processed": GREEN, "active": GREEN, "success": GREEN,
    "online": GREEN, "info": GREEN, "2xx": GREEN,
    # bad
    "failed": RED, "error": RED, "invalid": RED, "critical": PURPLE, "5xx": RED,
    # in between
    "partial_failed": ORANGE, "warn": ORANGE, "4xx": ORANGE, "missed": ORANGE, "skipped": YELLOW,
    "running": YELLOW, "processing": YELLOW, "pending": BLUE, "debug": BLUE, "3xx": BLUE,
    # inert
    "cancelled": GRAY, "disabled": GRAY, "unknown": GRAY, "inactive": GRAY,
}


def color_overrides(regex=False):
    """Fixed colours for status-named series so 'failed' is never green."""
    out = []
    for name, color in STATUS_COLORS.items():
        matcher = ({"id": "byRegexp", "options": f"(.* )?{name}"} if regex
                   else {"id": "byName", "options": name})
        out.append({"matcher": matcher,
                    "properties": [{"id": "color", "value": {"mode": "fixed", "fixedColor": color}}]})
    return out


def steps(*pairs, base="green"):
    out = [{"color": base, "value": None}]
    for color, value in pairs:
        out.append({"color": color, "value": value})
    return {"mode": "absolute", "steps": out}


# ----------------------------------------------------------------- targets
def prom(expr, legend="", instant=False, ref="A", table=False):
    t = {"refId": ref, "datasource": PROM, "expr": expr, "legendFormat": legend or "__auto",
         "range": not instant}
    if instant:
        t["instant"] = True
    if table:
        t["format"] = "table"
    return t


def sql(raw, fmt="table", ref="A"):
    return {"refId": ref, "datasource": PG, "rawSql": raw.strip(), "format": fmt,
            "rawQuery": True, "editorMode": "code"}


def loki(expr, legend="", instant=False, ref="A"):
    return {"refId": ref, "datasource": LOKI, "expr": expr, "legendFormat": legend,
            "queryType": "instant" if instant else "range", "editorMode": "code"}


# ----------------------------------------------------------------- layout
class Layout:
    def __init__(self):
        self.panels, self.y, self.x, self.row_h, self.next_id = [], 0, 0, 0, 1

    def _place(self, w, h):
        if self.x + w > 24:
            self.y += self.row_h
            self.x, self.row_h = 0, 0
        pos = {"x": self.x, "y": self.y, "w": w, "h": h}
        self.x += w
        self.row_h = max(self.row_h, h)
        return pos

    def row(self, title, collapsed=False):
        if self.x:
            self.y += self.row_h
        self.x, self.row_h = 0, 0
        self.panels.append({"id": self.next_id, "type": "row", "title": title, "collapsed": collapsed,
                            "gridPos": {"x": 0, "y": self.y, "w": 24, "h": 1}, "panels": []})
        self.next_id += 1
        self.y += 1

    def reserve(self):
        pid = self.next_id
        self.next_id += 1
        return pid

    def add(self, panel, w, h, pid=None):
        if pid is None:
            pid = self.reserve()
        panel["id"] = pid
        panel["gridPos"] = self._place(w, h)
        self.panels.append(panel)


# ----------------------------------------------------------------- panels
def stat(title, ds, targets, unit="short", thresholds=None, desc="", mappings=None, graph=False,
         text_mode="auto", decimals=None, color_mode="value"):
    defaults = {"unit": unit, "color": {"mode": "thresholds"},
                "thresholds": thresholds or steps(), "mappings": mappings or []}
    if decimals is not None:
        defaults["decimals"] = decimals
    return {"type": "stat", "title": title, "description": desc, "datasource": ds, "targets": targets,
            "fieldConfig": {"defaults": defaults, "overrides": []},
            "options": {"reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": False},
                        "colorMode": color_mode, "graphMode": "area" if graph else "none",
                        "justifyMode": "auto", "textMode": text_mode, "orientation": "auto",
                        "wideLayout": True, "showPercentChange": False}}


def series(title, ds, targets, unit="short", desc="", stacked=False, bars=False, min0=True,
           percent=False, colors=False, regex_colors=False, legend_table=False, decimals=None):
    custom = {"drawStyle": "bars" if bars else "line", "lineWidth": 1,
              "fillOpacity": 70 if bars else 12, "showPoints": "never", "spanNulls": False,
              "barAlignment": 0,
              "stacking": {"mode": "percent" if percent else ("normal" if stacked else "none"), "group": "A"}}
    defaults = {"unit": "percentunit" if percent else unit, "color": {"mode": "palette-classic"},
                "custom": custom}
    if decimals is not None:
        defaults["decimals"] = decimals
    if min0:
        defaults["min"] = 0
    overrides = color_overrides(regex=regex_colors) if (colors or regex_colors) else []
    legend = ({"displayMode": "table", "placement": "right", "showLegend": True,
               "calcs": ["lastNotNull", "max"]} if legend_table else
              {"displayMode": "list", "placement": "bottom", "showLegend": True})
    return {"type": "timeseries", "title": title, "description": desc, "datasource": ds,
            "targets": targets, "fieldConfig": {"defaults": defaults, "overrides": overrides},
            "options": {"legend": legend, "tooltip": {"mode": "multi", "sort": "desc"}}}


def table(title, ds, targets, desc="", units=None, sort=None, colored=None, bools=False,
          from_now=None, widths=None, links=None):
    """colored: column names whose cell text is coloured by STATUS_COLORS."""
    overrides = []
    for name, unit in (units or {}).items():
        overrides.append({"matcher": {"id": "byName", "options": name},
                          "properties": [{"id": "unit", "value": unit}]})
    for name in (from_now or []):
        overrides.append({"matcher": {"id": "byName", "options": name},
                          "properties": [{"id": "unit", "value": "dateTimeFromNow"}]})
    for name in (colored or []):
        overrides.append({"matcher": {"id": "byName", "options": name},
                          "properties": [
                              {"id": "custom.cellOptions", "value": {"type": "color-text"}},
                              {"id": "mappings", "value": [{"type": "value", "options": {
                                  k: {"color": v, "index": i} for i, (k, v) in enumerate(STATUS_COLORS.items())}}]}]})
    if bools:
        overrides.append({"matcher": {"id": "byType", "options": "boolean"},
                          "properties": [
                              {"id": "custom.cellOptions", "value": {"type": "color-text"}},
                              {"id": "custom.align", "value": "center"},
                              {"id": "mappings", "value": [{"type": "value", "options": {
                                  "true": {"text": "on", "color": GREEN, "index": 0},
                                  "false": {"text": "off", "color": GRAY, "index": 1}}}]}]})
    for name, width in (widths or {}).items():
        overrides.append({"matcher": {"id": "byName", "options": name},
                          "properties": [{"id": "custom.width", "value": width}]})
    for name, link in (links or {}).items():
        overrides.append({"matcher": {"id": "byName", "options": name},
                          "properties": [{"id": "links", "value": [link]}]})
    opts = {"showHeader": True, "cellHeight": "sm", "footer": {"show": False}}
    if sort:
        opts["sortBy"] = [{"displayName": sort[0], "desc": sort[1]}]
    return {"type": "table", "title": title, "description": desc, "datasource": ds, "targets": targets,
            "fieldConfig": {"defaults": {"custom": {"align": "auto", "filterable": True,
                                                    "cellOptions": {"type": "auto"}}},
                            "overrides": overrides},
            "options": opts}


def pie(title, ds, targets, desc="", colors=False):
    return {"type": "piechart", "title": title, "description": desc, "datasource": ds, "targets": targets,
            "fieldConfig": {"defaults": {"unit": "short", "color": {"mode": "palette-classic"}},
                            "overrides": color_overrides() if colors else []},
            "options": {"pieType": "donut",
                        "reduceOptions": {"values": True, "calcs": ["lastNotNull"], "fields": ""},
                        "legend": {"displayMode": "table", "placement": "right", "showLegend": True,
                                   "values": ["value", "percent"]},
                        "tooltip": {"mode": "single", "sort": "none"}}}


def bargauge(title, ds, targets, unit="short", desc="", values=False, thresholds=None):
    fc = {"unit": unit, "min": 0}
    if thresholds:
        fc.update({"color": {"mode": "thresholds"}, "thresholds": thresholds})
    else:
        fc["color"] = {"mode": "continuous-BlPu"}
    return {"type": "bargauge", "title": title, "description": desc, "datasource": ds, "targets": targets,
            "fieldConfig": {"defaults": fc, "overrides": []},
            "options": {"orientation": "horizontal", "displayMode": "basic", "showUnfilled": True,
                        "valueMode": "color", "namePlacement": "left", "sizing": "manual",
                        "minVizHeight": 16, "maxVizHeight": 24, "minVizWidth": 8,
                        "text": {"titleSize": 12, "valueSize": 14},
                        "reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": values}}}


def logs(title, expr, desc=""):
    return {"type": "logs", "title": title, "description": desc, "datasource": LOKI,
            "targets": [loki(expr)],
            "options": {"showTime": True, "showLabels": False, "showCommonLabels": False,
                        "wrapLogMessage": True, "prettifyLogMessage": False, "enableLogDetails": True,
                        "enableInfiniteScrolling": True, "dedupStrategy": "none",
                        "sortOrder": "Descending"}}


# ----------------------------------------------------------------- variables
def var_sql(name, label, query, multi=True, include_all=True, all_value=None, hide=0):
    v = {"name": name, "label": label, "type": "query", "datasource": PG, "query": query.strip(),
         "definition": query.strip(), "multi": multi, "includeAll": include_all, "refresh": 2,
         "sort": 1, "hide": hide, "current": {"selected": True, "text": ["All"], "value": ["$__all"]},
         "options": []}
    if all_value:
        v["allValue"] = all_value
    return v


def var_prom(name, label, query, all_value=".*"):
    return {"name": name, "label": label, "type": "query", "datasource": PROM,
            "query": {"query": query, "refId": "PrometheusVariableQueryEditor-VariableQuery", "qryType": 1},
            "definition": query, "multi": True, "includeAll": True, "allValue": all_value, "refresh": 2,
            "sort": 1, "current": {"selected": True, "text": ["All"], "value": ["$__all"]}, "options": []}


def var_loki_label(name, label, label_name):
    return {"name": name, "label": label, "type": "query", "datasource": LOKI,
            "query": {"type": 1, "label": label_name, "stream": "", "refId": "LokiVariableQueryEditor-VariableQuery"},
            "definition": f"label_values({label_name})", "multi": True, "includeAll": True,
            "allValue": ".+", "refresh": 2, "sort": 1,
            "current": {"selected": True, "text": ["All"], "value": ["$__all"]}, "options": []}


def var_custom(name, label, values, default, multi=False, include_all=False, all_value=None):
    opts = [{"text": t, "value": v, "selected": v == default} for t, v in values]
    v = {"name": name, "label": label, "type": "custom", "query": ",".join(f"{t} : {v}" for t, v in values),
         "multi": multi, "includeAll": include_all, "options": opts,
         "current": ({"selected": True, "text": ["All"], "value": ["$__all"]} if include_all and default == "$__all"
                     else {"selected": True, "text": next(t for t, v in values if v == default), "value": default})}
    if all_value:
        v["allValue"] = all_value
    return v


def var_prom_value(name, expr):
    """A hidden variable holding the value of a one-series PromQL `expr`,
    re-read on every dashboard load."""
    query = f"query_result({expr})"
    return {"name": name, "type": "query", "datasource": PROM, "hide": 2, "refresh": 1,
            "query": query, "definition": query,
            # query_result() lists each series as "{labels} value timestamp".
            "regex": "/ ([0-9.]+) [0-9]+$/",
            "current": {}, "options": []}


def stale_lock(var, default_seconds):
    """The stale-lock interval its worker uses, as SQL. The backend exports
    it (tigerduck_stale_lock_seconds); `default_seconds`, the setting's
    default, only stands in if Prometheus can't be reached."""
    return f"make_interval(secs => COALESCE(NULLIF('${{{var}}}', '')::float, {default_seconds}))"


def var_text(name, label, desc=""):
    return {"name": name, "label": label, "type": "textbox", "query": "", "description": desc,
            "current": {"selected": False, "text": "", "value": ""}, "options": [{"selected": True, "text": "", "value": ""}]}


def dashboard(uid, title, desc, panels, time_from, variables=(), refresh="30s"):
    return {"uid": uid, "title": title, "description": desc, "tags": ["tigerduck"], "timezone": "browser",
            "editable": True, "graphTooltip": 1, "refresh": refresh, "schemaVersion": 41, "version": 1,
            "time": {"from": time_from, "to": "now"}, "templating": {"list": list(variables)},
            "annotations": {"list": []},
            "links": [{"type": "dashboards", "tags": ["tigerduck"], "asDropdown": True, "title": "TigerDuck",
                       "includeVars": False, "keepTime": True, "icon": "external link", "targetBlank": False}],
            "panels": panels}


def taipei_day(col):
    """`col`'s day in Taiwan time. $__timeGroup('1d') floors to UTC
    midnight, which would cut every day at 08:00 local time."""
    return f"date_trunc('day', {col}, 'Asia/Taipei')"


def per_day(counts, by_metric):
    """A daily bar chart's query, from `counts`: a SELECT of `day` (made
    with taipei_day), `value` and, when by_metric, `metric`. Every day in
    the range gets a row, at 0 when nothing happened: Grafana sizes bars by
    the closest two points, so a missing day would stretch its neighbours
    across it."""
    days = f"""days AS (
    SELECT generate_series({taipei_day("$__timeFrom()::timestamptz")}, $__timeTo()::timestamptz, interval '1 day') AS day
)"""
    if not by_metric:
        return f"""WITH {days},
counts AS (
{counts.strip()}
)
SELECT d.day AS "time", COALESCE(c.value, 0) AS value
FROM days d
LEFT JOIN counts c ON c.day = d.day
ORDER BY 1"""
    return f"""WITH {days},
counts AS (
{counts.strip()}
),
metrics AS (SELECT DISTINCT metric FROM counts)
SELECT d.day AS "time", m.metric, COALESCE(c.value, 0) AS value
FROM days d
CROSS JOIN metrics m
LEFT JOIN counts c ON c.day = d.day AND c.metric = m.metric
ORDER BY 1"""


def dash_link(title, uid):
    return {"title": title, "url": f"/d/{uid}?${{__url_time_range}}"}


dashboards = {}

# ======================================================================= Overview
L = Layout()
L.row("Users and devices")
L.add(stat("Online now", PROM, [prom('sum(tigerduck_devices_seen{window="15m"})', instant=False)],
           graph=True, desc="Devices that talked to the backend in the last 15 minutes."), 4, 4)
L.add(stat("Active, 24h", PROM, [prom('sum(tigerduck_devices_seen{window="24h"})')], graph=True), 4, 4)
L.add(stat("Active, 14 days", PROM, [prom('sum(tigerduck_devices_seen{window="14d"})')], graph=True), 4, 4)
L.add(stat("Devices", PROM, [prom("sum(tigerduck_devices)")], graph=True), 4, 4)
L.add(stat("Students", PROM, [prom('sum(tigerduck_users{kind="student", status="active"})')], graph=True,
           desc="Active users signed in with a student ID."), 4, 4)
L.add(stat("Re-login needed", PROM, [prom('sum(tigerduck_external_accounts{credential_status!="active"}) or vector(0)')],
           thresholds=steps(("orange", 1)),
           desc="NTUST accounts whose stored credential stopped working. Their server-side sync is paused until they sign in again."), 4, 4)

L.row("Health")
L.add(stat("Scrape targets", PROM, [prom("up", "{{job}}")],
           thresholds={"mode": "absolute", "steps": [{"color": "red", "value": None}, {"color": "green", "value": 1}]},
           mappings=[{"type": "value", "options": {"0": {"text": "DOWN"}, "1": {"text": "UP"}}}],
           text_mode="value_and_name", color_mode="background",
           desc="Whether Prometheus reached each exporter on its last scrape. backend DOWN means the API process is down or its metrics port is closed."), 8, 4)
L.add(stat("Requests / s", PROM, [prom("sum(rate(tigerduck_http_requests_total[5m]))")], unit="reqps", graph=True,
           decimals=2), 4, 4)
L.add(stat("5xx share", PROM, [prom('sum(rate(tigerduck_http_requests_total{status=~"5.."}[5m])) / sum(rate(tigerduck_http_requests_total[5m])) or vector(0)')],
           unit="percentunit", thresholds=steps(("orange", 0.01), ("red", 0.05)), graph=True), 4, 4)
L.add(stat("p95 latency", PROM, [prom("histogram_quantile(0.95, sum by (le) (rate(tigerduck_http_request_duration_seconds_bucket[5m])))")],
           unit="s", thresholds=steps(("orange", 1), ("red", 3)), graph=True), 4, 4)
L.add(stat("App errors, 1h", LOKI, [loki('sum(count_over_time({service=~"backend|portal|postgres"} | detected_level=~"error|critical" [1h])) or vector(0)', instant=True)],
           thresholds=steps(("orange", 1), ("red", 50)),
           desc="Error and critical log lines from the backend, portal and Postgres in the last hour. The Logs dashboard has every container."), 4, 4)
L.add(stat("Push delay", PROM, [prom("tigerduck_push_oldest_due_seconds")], unit="s",
           thresholds=steps(("orange", 60), ("red", 300)),
           desc="How late the most overdue pending push is. Climbing means the push tick is stuck."), 4, 4)
L.add(stat("Push failed, 1h", PROM, [prom('sum(tigerduck_push_jobs_finished_last_hour{status=~"failed|partial_failed"}) or vector(0)')],
           thresholds=steps(("orange", 1), ("red", 20))), 4, 4)
L.add(stat("Sync overdue", PROM, [prom("sum(tigerduck_sync_jobs_overdue) or vector(0)")],
           thresholds=steps(("orange", 1), ("red", 10)),
           desc="Pending sync jobs more than 10 minutes past their run time."), 4, 4)
L.add(stat("Bulletin scrape", PROM, [prom('time() - (max(tigerduck_scheduler_job_last_success_timestamp_seconds{job_id="bulletin_scrape"}) or max(process_start_time_seconds{job="backend"}))')], unit="s",
           thresholds=steps(("orange", 1800), ("red", 7200)),
           desc='Since the bulletin scraper last ran without an error. It runs every 10 minutes by default; right after a backend restart this counts from the restart until the first run.'), 4, 4)
L.add(stat("DB conns used", PROM, [prom("sum(pg_stat_activity_count) / max(pg_settings_max_connections)")],
           unit="percentunit", thresholds=steps(("orange", 0.7), ("red", 0.9))), 4, 4)
L.add(stat("Backend memory", PROM, [prom('process_resident_memory_bytes{job="backend"}')], unit="bytes", graph=True), 4, 4)

L.row("Trends")
L.add(series("Online devices by platform", PROM, [prom('sum by (platform) (tigerduck_devices_seen{window="15m"})', "{{platform}}")],
             stacked=True), 12, 8)
L.add(series("Requests / s by status", PROM, [prom(
    'sum by (class) (label_replace(rate(tigerduck_http_requests_total[$__rate_interval]), "class", "${1}xx", "status", "(\\\\d).."))', "{{class}}")],
    unit="reqps", stacked=True, colors=True), 12, 8)
L.add(series("Push jobs finished per hour", PROM, [prom("sum by (status) (tigerduck_push_jobs_finished_last_hour)", "{{status}}")],
             colors=True, desc="Rolling one-hour count, sampled every 30 seconds."), 12, 8)
L.add(series("Errors in logs by service", LOKI, [loki('sum by (service) (count_over_time({service=~"backend|portal|postgres"} | detected_level=~"error|critical" [$__auto]))', "{{service}}")],
             bars=True, stacked=True), 12, 8)

L.row("Recent errors")
L.add(logs("Errors and warnings: backend, portal, Postgres", '{service=~"backend|portal|postgres"} | detected_level=~"error|critical|warn"'), 24, 12)
dashboards["overview"] = dashboard(
    "tigerduck-overview", "Overview", "The whole stack at a glance. Each section links to its own dashboard.",
    L.panels, "now-24h", refresh="1m")

# ======================================================================= Devices
DEV_FILTER = """
ud.deleted_at IS NULL
  AND ud.platform IN (${platform:sqlstring})
  AND COALESCE(ud.app_version, 'unknown') IN (${app_version:sqlstring})
  AND (${search:sqlstring} = ''
       OR concat_ws(' ', ud.id::text, ud.client_device_id, u.student_id, ud.device_model)
          ILIKE '%' || ${search:sqlstring} || '%')
"""
FROM_DEV = "FROM user_devices ud JOIN users u ON u.id = ud.user_id"
PLATFORM_RE = 'platform=~"${platform:regex}"'

L = Layout()
L.row("Now")
L.add(stat("Online", PG, [sql(f"SELECT count(*) AS \"online\" {FROM_DEV} WHERE {DEV_FILTER} AND ud.last_seen_at > now() - '${{online_window}}'::interval")],
           desc="Devices whose last request (sync poll, upload, registration) is within the 'Online = seen within' window.",
           thresholds=steps(base=GREEN)), 3, 4)
L.add(stat("Active", PG, [sql(f"SELECT count(*) AS \"active\" {FROM_DEV} WHERE {DEV_FILTER} AND ud.last_seen_at > now() - '${{active_window}}'::interval")],
           desc="Devices seen within the 'Active = seen within' window (14 days by default)."), 3, 4)
L.add(stat("Active 24h", PG, [sql(f"SELECT count(*) AS \"24h\" {FROM_DEV} WHERE {DEV_FILTER} AND ud.last_seen_at > now() - interval '24 hours'")]), 3, 4)
L.add(stat("Devices", PG, [sql(f"SELECT count(*) AS \"devices\" {FROM_DEV} WHERE {DEV_FILTER}")]), 3, 4)
L.add(stat("Students", PG, [sql(f"SELECT count(DISTINCT u.id) AS \"students\" {FROM_DEV} WHERE {DEV_FILTER} AND u.student_id IS NOT NULL")]), 3, 4)
L.add(stat("Push on", PG, [sql(f"SELECT count(*) FILTER (WHERE ud.server_push_enabled)::float / NULLIF(count(*), 0) AS \"push on\" {FROM_DEV} WHERE {DEV_FILTER}")],
           unit="percentunit", decimals=0), 3, 4)
L.add(stat("Sessions", PG, [sql("SELECT count(*) AS \"sessions\" FROM auth_sessions WHERE revoked_at IS NULL AND expires_at > now()")],
           desc="Refresh-token sessions neither revoked nor expired. Not affected by the filters."), 3, 4)
L.add(stat("Token reuse", PG, [sql("SELECT count(*) AS \"reuse\" FROM auth_sessions WHERE reuse_detected_at > now() - interval '24 hours'")],
           thresholds=steps(("red", 1)),
           desc="A rotated refresh token presented again: a client bug or a stolen token. Not affected by the filters."), 3, 4)

L.row("Over time")
L.add(series("Online devices", PROM, [prom(f'sum by (platform) (tigerduck_devices_seen{{window="$online_window", {PLATFORM_RE}}})', "{{platform}}")],
             stacked=True, desc="Sampled every 30 seconds. Starts when monitoring was first deployed."), 12, 8)
L.add(series("Active devices", PROM, [prom(f'sum by (window) (tigerduck_devices_seen{{window=~"24h|7d|$active_window|30d", {PLATFORM_RE}}})', "seen within {{window}}")],
             desc="Daily, weekly and monthly active devices."), 12, 8)
L.add(series("Registered devices", PROM, [prom(f"sum by (platform) (tigerduck_devices{{{PLATFORM_RE}}})", "{{platform}}")], stacked=True), 8, 8)
L.add(series("App version adoption", PROM, [prom(f"sum by (app_version) (tigerduck_devices_by_app_version{{{PLATFORM_RE}}})", "{{app_version}}")],
             percent=True), 8, 8)
L.add(series("Sign-in sessions created per hour", PG, [sql("""
SELECT $__timeGroupAlias(created_at, '1h', 0), count(*) AS "sessions"
FROM auth_sessions
WHERE $__timeFilter(created_at)
GROUP BY 1
ORDER BY 1
""", fmt="time_series")], bars=True,
    desc="Logins plus refresh-token rotations. Access tokens last 15 minutes, so an app in use rotates a few times an hour: a rough activity signal."), 8, 8)

L.row("Breakdown")
L.add(pie("Platform", PG, [sql(f"SELECT ud.platform AS \"platform\", count(*) AS \"devices\" {FROM_DEV} WHERE {DEV_FILTER} GROUP BY 1 ORDER BY 2 DESC")]), 6, 8)
L.add(bargauge("App version", PG, [sql(f"SELECT ud.platform || ' ' || COALESCE(ud.app_version, '?') AS \"version\", count(*) AS \"devices\" {FROM_DEV} WHERE {DEV_FILTER} GROUP BY 1 ORDER BY 2 DESC")], values=True), 6, 8)
L.add(bargauge("OS version", PG, [sql(f"SELECT CASE WHEN ud.os_version ILIKE ud.platform || '%' THEN ud.os_version ELSE ud.platform || ' ' || COALESCE(ud.os_version, '?') END AS \"os\", count(*) AS \"devices\" {FROM_DEV} WHERE {DEV_FILTER} GROUP BY 1 ORDER BY 2 DESC")], values=True), 6, 8)
L.add(bargauge("Device model", PG, [sql(f"SELECT COALESCE(ud.device_model, 'unknown') AS \"model\", count(*) AS \"devices\" {FROM_DEV} WHERE {DEV_FILTER} GROUP BY 1 ORDER BY 2 DESC LIMIT 15")], values=True), 6, 8)
L.add(bargauge("Switches turned on", PG, [sql(f"""
SELECT s.setting AS "setting", count(*) FILTER (WHERE s.enabled) AS "devices"
{FROM_DEV}
CROSS JOIN LATERAL (VALUES
    ('server push', ud.server_push_enabled), ('cloud sync', ud.cloud_sync_enabled),
    ('bulletin push', ud.bulletin_push_enabled), ('live activity', ud.sync_live_activity),
    ('assignment reminders', ud.sync_assignment_reminders), ('sync courses', ud.sync_courses),
    ('sync course colors', ud.sync_course_colors), ('sync course names', ud.sync_course_names),
    ('sync assignments', ud.sync_assignments)
) AS s(setting, enabled)
WHERE {DEV_FILTER}
GROUP BY 1
ORDER BY 2 DESC
""")], values=True, desc="Per-device switches from the app's settings."), 8, 8)
L.add(bargauge("Push tokens", PG, [sql(f"""
SELECT t.provider || ' ' || t.token_kind || ' (' || t.status || ')' AS "token", count(*) AS "tokens"
FROM device_push_tokens t
JOIN user_devices ud ON ud.id = t.device_id
JOIN users u ON u.id = ud.user_id
WHERE {DEV_FILTER}
GROUP BY 1
ORDER BY 2 DESC
""")], values=True, desc="push_to_start tokens start Live Activities; standard tokens carry every other push."), 8, 8)
L.add(pie("Locale", PG, [sql(f"SELECT COALESCE(ud.locale, 'unknown') AS \"locale\", count(*) AS \"devices\" {FROM_DEV} WHERE {DEV_FILTER} GROUP BY 1 ORDER BY 2 DESC")]), 8, 8)

L.row("Devices")
L.add(table("Devices", PG, [sql(f"""
SELECT
    CASE WHEN ud.last_seen_at > now() - '${{online_window}}'::interval THEN 'online'
         WHEN ud.last_seen_at > now() - '${{active_window}}'::interval THEN 'active'
         ELSE 'inactive' END AS "status",
    ud.last_seen_at AS "last seen",
    COALESCE(u.student_id, u.id::text) AS "user",
    ud.platform AS "platform",
    ud.device_model AS "model",
    ud.app_version AS "app",
    ud.os_version AS "os",
    ud.locale AS "locale",
    ud.server_push_enabled AS "push",
    ud.cloud_sync_enabled AS "cloud sync",
    ud.bulletin_push_enabled AS "bulletins",
    ud.sync_live_activity AS "live activity",
    ud.sync_assignment_reminders AS "reminders",
    EXISTS (SELECT 1 FROM device_push_tokens t WHERE t.device_id = ud.id AND t.status = 'active'
            AND t.provider = 'apns' AND t.token_kind = 'standard') AS "apns",
    EXISTS (SELECT 1 FROM device_push_tokens t WHERE t.device_id = ud.id AND t.status = 'active'
            AND t.token_kind = 'push_to_start') AS "pts",
    EXISTS (SELECT 1 FROM device_push_tokens t WHERE t.device_id = ud.id AND t.status = 'active'
            AND t.provider = 'fcm') AS "fcm",
    (SELECT t.environment FROM device_push_tokens t WHERE t.device_id = ud.id AND t.status = 'active'
     ORDER BY (t.token_kind = 'standard') DESC, t.id LIMIT 1) AS "apns env",
    ud.last_login_at AS "last login",
    ud.created_at AS "registered",
    ud.id::text AS "device id",
    ud.client_device_id AS "client id"
{FROM_DEV}
WHERE {DEV_FILTER}
ORDER BY ud.last_seen_at DESC NULLS LAST
LIMIT 1000
""")], colored=["status"], bools=True, from_now=["last seen", "last login"],
    widths={"status": 80, "push": 60, "cloud sync": 85, "bulletins": 80, "live activity": 95, "reminders": 85,
            "apns": 60, "pts": 50, "fcm": 50},
    desc="The portal's device list, plus switches and last-seen. Filtered by the variables above; the search box matches device ID, client ID, student ID and model."), 24, 14)
L.add(table("Device lists", PG, [sql("""
SELECT l.name AS "list", l.description AS "description", count(m.device_id) AS "members",
       l.created_at AS "created", l.updated_at AS "updated"
FROM device_lists l
LEFT JOIN device_list_members m ON m.list_id = l.id
GROUP BY l.id
ORDER BY l.name
""")], desc="Named cohorts for custom pushes, managed from the portal's Lists tab."), 12, 6)
L.add(series("Devices registered per day", PG, [sql(per_day(f"""
SELECT {taipei_day("ud.created_at")} AS day, ud.platform AS metric, count(*) AS value
{FROM_DEV}
WHERE $__timeFilter(ud.created_at) AND ud.platform IN (${{platform:sqlstring}})
GROUP BY 1, 2
""", by_metric=True), fmt="time_series")], bars=True, stacked=True), 12, 6)
L.add(stat("Legacy registrations", PG, [sql("SELECT count(*) AS \"rows\" FROM device_registrations")],
           desc="Rows in the pre-v3 device_registrations table, still read by the anonymous bulletin dispatcher and custom-push targeting."), 4, 4)

devices_vars = [
    var_sql("platform", "Platform", "SELECT DISTINCT platform FROM user_devices WHERE deleted_at IS NULL ORDER BY 1"),
    var_sql("app_version", "App version",
            "SELECT DISTINCT COALESCE(app_version, 'unknown') FROM user_devices WHERE deleted_at IS NULL AND platform IN (${platform:sqlstring}) ORDER BY 1"),
    var_custom("online_window", "Online = seen within",
               [("5 minutes", "5m"), ("15 minutes", "15m"), ("1 hour", "1h"), ("24 hours", "24h")], "15m"),
    var_custom("active_window", "Active = seen within",
               [("7 days", "7d"), ("14 days", "14d"), ("30 days", "30d")], "14d"),
    var_text("search", "Search", "Device ID, client ID, student ID or model"),
]
dashboards["devices"] = dashboard(
    "tigerduck-devices", "Devices", "Everything on the portal's Devices tab, plus who is online and active.",
    L.panels, "now-7d", devices_vars)

# ======================================================================= Moodle sync
JOB_FILTER = "j.job_type IN (${job_type:sqlstring})"
# The worker claims a job only when its policy is enabled and inside its
# active window (server/syncjobs/executor.py); same rule here.
POLICY_LIVE = ("p.enabled AND (p.active_from IS NULL OR p.active_from <= now()) "
               "AND (p.active_until IS NULL OR p.active_until > now())")
STUDENT_FILTER = "(${search:sqlstring} = '' OR COALESCE(u.student_id, '') ILIKE '%' || ${search:sqlstring} || '%')"
L = Layout()
L.row("Now")
L.add(stat("Accounts ok", PG, [sql("SELECT count(*) AS \"ok\" FROM external_accounts WHERE credential_status = 'active'")]), 3, 4)
L.add(stat("Re-login", PG, [sql("SELECT count(*) AS \"invalid\" FROM external_accounts WHERE credential_status <> 'active'")],
           thresholds=steps(("orange", 1)),
           desc="NTUST credentials that stopped working. Sync for these students is disabled until they sign in again in the app."), 3, 4)
L.add(stat("Pending", PG, [sql(f"SELECT count(*) AS \"pending\" FROM sync_jobs j WHERE {JOB_FILTER} AND j.status = 'pending'")]), 3, 4)
L.add(stat("Running", PG, [sql(f"SELECT count(*) AS \"running\" FROM sync_jobs j WHERE {JOB_FILTER} AND j.status = 'running'")],
           thresholds=steps(base=YELLOW)), 3, 4)
L.add(stat("Overdue", PG, [sql(f"""
SELECT count(*) AS "overdue"
FROM sync_jobs j
JOIN sync_policies p ON p.job_type = j.job_type
WHERE {JOB_FILTER} AND j.status = 'pending' AND j.run_after < now() - interval '10 minutes'
  AND {POLICY_LIVE}
""")],
           thresholds=steps(("orange", 1), ("red", 10)),
           desc="Pending jobs more than 10 minutes past run_after, counting only types the worker would claim (policy enabled and inside its active window). The sync tick runs every 30 seconds, so these should be picked up long before."), 3, 4)
L.add(stat("Stuck", PG, [sql(f"SELECT count(*) AS \"stuck\" FROM sync_jobs j WHERE {JOB_FILTER} AND j.status = 'running' AND j.locked_at < now() - {stale_lock('sync_stale_lock', 600)}")],
           thresholds=steps(("red", 1)),
           desc="Running for longer than the worker's stale-lock limit (TIGERDUCK_SYNC_JOB_STALE_LOCK_MINUTES, read from the backend)."), 3, 4)
L.add(stat("Runs", PG, [sql(f"SELECT count(*) AS \"runs\" FROM sync_runs r JOIN sync_jobs j ON j.id = r.sync_job_id WHERE {JOB_FILTER} AND $__timeFilter(r.started_at)")],
           desc="Sync runs started in the dashboard's time range."), 3, 4)
L.add(stat("Failed runs", PG, [sql(f"SELECT count(*) AS \"failed\" FROM sync_runs r JOIN sync_jobs j ON j.id = r.sync_job_id WHERE {JOB_FILTER} AND $__timeFilter(r.started_at) AND r.status = 'failed'")],
           thresholds=steps(("orange", 1), ("red", 10))), 3, 4)

L.row("Over time")
L.add(series("Runs per hour", PG, [sql(f"""
SELECT $__timeGroupAlias(r.started_at, '1h', 0), r.status AS metric, count(*) AS value
FROM sync_runs r JOIN sync_jobs j ON j.id = r.sync_job_id
WHERE $__timeFilter(r.started_at) AND {JOB_FILTER}
GROUP BY 1, 2
ORDER BY 1
""", fmt="time_series")], bars=True, stacked=True, colors=True), 12, 8)
L.add(series("Run duration", PG, [sql(f"""
SELECT $__timeGroupAlias(r.started_at, '1h'),
       avg(extract(epoch FROM r.finished_at - r.started_at)) AS "average",
       max(extract(epoch FROM r.finished_at - r.started_at)) AS "longest"
FROM sync_runs r JOIN sync_jobs j ON j.id = r.sync_job_id
WHERE $__timeFilter(r.started_at) AND r.finished_at IS NOT NULL AND {JOB_FILTER}
GROUP BY 1
ORDER BY 1
""", fmt="time_series")], unit="s"), 12, 8)
L.add(series("Items fetched and changed per hour", PG, [sql(f"""
SELECT $__timeGroupAlias(r.started_at, '1h', 0),
       sum(r.fetched_count) AS "fetched", sum(r.changed_count) AS "changed"
FROM sync_runs r JOIN sync_jobs j ON j.id = r.sync_job_id
WHERE $__timeFilter(r.started_at) AND {JOB_FILTER}
GROUP BY 1
ORDER BY 1
""", fmt="time_series")], bars=True), 12, 8)
L.add(series("Jobs by status", PROM, [prom('sum by (status) (tigerduck_sync_jobs{job_type=~"${job_type:regex}"})', "{{status}}")],
             stacked=True, colors=True, desc="Sampled every 30 seconds."), 12, 8)

L.row("Policies and jobs")
L.add(table("Sync policies", PG, [sql("""
SELECT job_type AS "job type", enabled AS "enabled", default_interval_seconds AS "interval",
       active_from AS "active from", active_until AS "active until", priority AS "priority",
       max_attempts AS "max attempts", updated_at AS "updated"
FROM sync_policies
ORDER BY job_type
""")], bools=True, units={"interval": "s"}, desc="Operator-tunable switches per sync type."), 24, 7)
L.add(table("Jobs", PG, [sql(f"""
SELECT COALESCE(u.student_id, u.id::text) AS "student",
       j.job_type AS "job type",
       j.status AS "status",
       j.run_after AS "next run",
       j.last_success_at AS "last success",
       j.last_failure_at AS "last failure",
       j.attempts || '/' || j.max_attempts AS "attempts",
       j.locked_by AS "locked by",
       left(j.last_error, 200) AS "last error"
FROM sync_jobs j
JOIN users u ON u.id = j.user_id
WHERE {JOB_FILTER} AND {STUDENT_FILTER}
ORDER BY (j.status = 'running') DESC, (j.status = 'failed') DESC, j.run_after
LIMIT 500
""")], colored=["status"], from_now=["next run", "last success", "last failure"],
    desc="One row per student and sync type. Running and failed first."), 24, 10)

L.row("Failures and accounts")
L.add(table("Failed runs", PG, [sql(f"""
SELECT r.started_at AS "started",
       COALESCE(u.student_id, u.id::text) AS "student",
       j.job_type AS "job type",
       extract(epoch FROM r.finished_at - r.started_at) AS "took",
       left(r.error, 300) AS "error"
FROM sync_runs r
JOIN sync_jobs j ON j.id = r.sync_job_id
JOIN users u ON u.id = r.user_id
WHERE r.status = 'failed' AND $__timeFilter(r.started_at) AND {JOB_FILTER} AND {STUDENT_FILTER}
ORDER BY r.started_at DESC
LIMIT 200
""")], units={"took": "s"}), 16, 8)
L.add(bargauge("Failure reasons", PG, [sql(f"""
SELECT split_part(COALESCE(r.error, 'unknown'), ':', 1) AS "reason", count(*) AS "runs"
FROM sync_runs r JOIN sync_jobs j ON j.id = r.sync_job_id
WHERE r.status = 'failed' AND $__timeFilter(r.started_at) AND {JOB_FILTER}
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
""")], values=True, thresholds=steps(base=RED), desc="Failed runs in range, by error prefix."), 8, 8)
L.add(table("NTUST accounts", PG, [sql(f"""
SELECT COALESCE(u.student_id, u.id::text) AS "student",
       a.provider AS "provider",
       a.credential_status AS "credential",
       a.last_auth_success_at AS "last sign-in ok",
       a.last_auth_failure_at AS "last sign-in failed",
       left(a.last_auth_error, 200) AS "error"
FROM external_accounts a
JOIN users u ON u.id = a.user_id
WHERE {STUDENT_FILTER}
ORDER BY (a.credential_status <> 'active') DESC, a.last_auth_failure_at DESC NULLS LAST
LIMIT 500
""")], colored=["credential"], from_now=["last sign-in ok", "last sign-in failed"]), 24, 8)

L.row("Activity log")
L.add(series("Log entries per hour", PG, [sql(f"""
SELECT $__timeGroupAlias(e.ts, '1h', 0), e.source AS metric, count(*) AS value
FROM sync_log_entries e
WHERE $__timeFilter(e.ts) AND e.source IN (${{log_source:sqlstring}}) AND e.level IN (${{log_level:sqlstring}})
GROUP BY 1, 2
ORDER BY 1
""", fmt="time_series")], bars=True, stacked=True), 24, 6)
L.add(table("Activity log", PG, [sql(f"""
SELECT e.ts AS "time",
       COALESCE(u.student_id, e.user_id::text) AS "student",
       d.platform AS "device",
       e.level AS "level",
       e.source AS "source",
       e.message AS "message",
       left(e.detail::text, 300) AS "detail"
FROM sync_log_entries e
LEFT JOIN users u ON u.id = e.user_id
LEFT JOIN user_devices d ON d.id = e.device_id
WHERE $__timeFilter(e.ts)
  AND e.source IN (${{log_source:sqlstring}})
  AND e.level IN (${{log_level:sqlstring}})
  AND {STUDENT_FILTER}
  AND (${{message:sqlstring}} = '' OR e.message ILIKE '%' || ${{message:sqlstring}} || '%')
ORDER BY e.ts DESC
LIMIT 500
""")], desc="The per-user sync log (sync_log_entries) the apps and executor write. Newest first, 500 rows max."), 24, 12)

sync_vars = [
    var_sql("job_type", "Job type", "SELECT job_type FROM sync_policies ORDER BY 1"),
    var_text("search", "Student ID"),
    var_sql("log_source", "Log source", "SELECT DISTINCT source FROM sync_log_entries ORDER BY 1"),
    var_sql("log_level", "Log level", "SELECT DISTINCT level FROM sync_log_entries ORDER BY 1"),
    var_text("message", "Log message"),
    var_prom_value("sync_stale_lock", 'max(tigerduck_stale_lock_seconds{queue="sync"})'),
]
dashboards["moodle-sync"] = dashboard(
    "tigerduck-sync", "Moodle sync", "Server-side academic sync: policies, per-student jobs, runs, accounts and the activity log.",
    L.panels, "now-7d", sync_vars)

# ======================================================================= Push
CH = "channel IN (${channel:sqlstring})"
DUE = "status = 'pending' AND fire_at <= now() AND available_at <= now()"
RETENTION = " Finished jobs (and their deliveries) are pruned after push_job_retention_days, 7 by default."
L = Layout()
L.row("Now")
L.add(stat("Due, not yet sent", PG, [sql(f'SELECT count(*) AS "due" FROM push_jobs WHERE {DUE} AND {CH}')],
           desc="Pending jobs whose time has come. The push tick runs every few seconds, so this should hover near 0.",
           thresholds=steps(("orange", 10), ("red", 100))), 4, 4)
L.add(stat("Oldest due job", PG, [sql(f'SELECT COALESCE(extract(epoch FROM now() - min(fire_at)), 0) AS "age" FROM push_jobs WHERE {DUE} AND {CH}')],
           unit="s", thresholds=steps(("orange", 60), ("red", 300)),
           desc="How late the most overdue pending job is. Climbing means the push tick is stuck or not running."), 4, 4)
L.add(stat("Scheduled", PG, [sql(f"SELECT count(*) AS \"scheduled\" FROM push_jobs WHERE status = 'pending' AND fire_at > now() AND {CH}")],
           desc="Pending jobs set to fire later.", thresholds=steps(base=BLUE)), 4, 4)
L.add(stat("Stuck processing", PG, [sql(f"SELECT count(*) AS \"stuck\" FROM push_jobs WHERE status = 'processing' AND locked_at < now() - {stale_lock('push_stale_lock', 300)} AND {CH}")],
           thresholds=steps(("red", 1)),
           desc="Jobs claimed longer ago than the worker's stale-lock limit (TIGERDUCK_PUSH_JOB_STALE_LOCK_MINUTES, read from the backend) and never finished."), 4, 4)
L.add(stat("Failed in range", PG, [sql(f"SELECT count(*) AS \"failed\" FROM push_jobs WHERE status IN ('failed', 'partial_failed') AND $__timeFilter(updated_at) AND {CH}")],
           thresholds=steps(("orange", 1), ("red", 20))), 4, 4)
L.add(stat("Sent in range", PG, [sql(f"SELECT count(*) AS \"sent\" FROM push_jobs WHERE status = 'sent' AND $__timeFilter(sent_at) AND {CH}")]), 4, 4)

L.row("Over time")
L.add(series("Job outcomes per hour", PG, [sql(f"""
SELECT $__timeGroupAlias(updated_at, '1h', 0), status AS metric, count(*) AS value
FROM push_jobs
WHERE $__timeFilter(updated_at) AND status IN ('sent', 'partial_failed', 'failed', 'cancelled') AND {CH}
GROUP BY 1, 2
ORDER BY 1
""", fmt="time_series")], bars=True, stacked=True, colors=True, desc="Jobs by the hour they finished." + RETENTION), 12, 8)
L.add(series("Deliveries per hour", PG, [sql("""
SELECT $__timeGroupAlias(d.updated_at, '1h', 0), d.provider || ' ' || d.status AS metric, count(*) AS value
FROM push_deliveries d
JOIN push_jobs j ON j.id = d.push_job_id
WHERE $__timeFilter(d.updated_at) AND d.status <> 'pending'
  AND d.provider IN (${provider:sqlstring}) AND j.channel IN (${channel:sqlstring})
GROUP BY 1, 2
ORDER BY 1
""", fmt="time_series")], bars=True, stacked=True, regex_colors=True,
    desc="One delivery per device token a job went to, by APNs / FCM and outcome." + RETENTION), 12, 8)
L.add(series("Queue", PROM, [prom('sum by (status) (tigerduck_push_jobs{channel=~"${channel:regex}"})', "{{status}}")],
             stacked=True, colors=True, desc="Rows in push_jobs by status, sampled every 30 seconds." + RETENTION), 12, 8)
L.add(series("Due backlog", PROM, [prom("tigerduck_push_jobs_due", "due jobs"),
                                   prom("tigerduck_push_oldest_due_seconds", "oldest due (s)", ref="B")],
             desc="Both should sit at zero apart from brief blips."), 12, 8)
L.add(series("APNs / FCM send time, p95", PROM, [prom(
    "histogram_quantile(0.95, sum by (le, provider) (rate(tigerduck_push_send_duration_seconds_bucket[$__rate_interval])))", "{{provider}}")],
    unit="s", desc="From the backend's own metrics: how long a single send to Apple or Google takes."), 12, 8)
L.add(series("APNs / FCM sends / s by outcome", PROM, [prom(
    "sum by (provider, outcome) (rate(tigerduck_push_send_duration_seconds_count[$__rate_interval]))", "{{provider}} {{outcome}}")],
    unit="ops", stacked=True, regex_colors=True), 12, 8)

L.row("Details")
L.add(table("Jobs by channel", PG, [sql(f"""
SELECT channel AS "channel",
       count(*) FILTER (WHERE status = 'pending') AS "pending",
       count(*) FILTER (WHERE status = 'processing') AS "processing",
       count(*) FILTER (WHERE status = 'sent') AS "sent",
       count(*) FILTER (WHERE status = 'partial_failed') AS "partial failed",
       count(*) FILTER (WHERE status = 'failed') AS "failed",
       count(*) FILTER (WHERE status = 'cancelled') AS "cancelled"
FROM push_jobs
WHERE {CH}
GROUP BY channel
ORDER BY channel
""")], desc="Every job currently in the table." + RETENTION), 12, 7)
L.add(table("Jobs by scenario", PG, [sql(f"""
SELECT channel AS "channel", scenario AS "scenario", count(*) AS "jobs",
       count(*) FILTER (WHERE status IN ('failed', 'partial_failed')) AS "failed",
       max(updated_at) AS "last activity"
FROM push_jobs
WHERE {CH}
GROUP BY 1, 2
ORDER BY 3 DESC
""")], from_now=["last activity"]), 12, 7)
L.add(table("Delivery failures", PG, [sql("""
SELECT provider AS "provider", token_kind AS "token", COALESCE(failure_code, '-') AS "code",
       count(*) AS "count", max(updated_at) AS "last seen"
FROM push_deliveries
WHERE status = 'failed' AND $__timeFilter(updated_at) AND provider IN (${provider:sqlstring})
GROUP BY 1, 2, 3
ORDER BY "count" DESC
""")], from_now=["last seen"], desc="Failed deliveries in the time range, by provider and failure code."), 12, 7)
L.add(table("Custom pushes", PG, [sql("""
SELECT created_at AS "sent", title AS "title", kind AS "kind", target_classes AS "targets", total AS "devices"
FROM custom_push_sends
WHERE $__timeFilter(created_at)
ORDER BY created_at DESC
LIMIT 100
""")], desc="Operator pushes sent from the portal's Custom push page."), 12, 7)
L.add(table("Recent failed jobs", PG, [sql(f"""
SELECT j.updated_at AS "updated", j.id AS "id", COALESCE(u.student_id, j.user_id::text) AS "student",
       j.channel AS "channel", j.scenario AS "scenario", j.status AS "status",
       j.attempts || '/' || j.max_attempts AS "attempts", left(j.last_error, 300) AS "last error"
FROM push_jobs j
LEFT JOIN users u ON u.id = j.user_id
WHERE j.status IN ('failed', 'partial_failed') AND j.{CH}
  AND (${{search:sqlstring}} = '' OR concat_ws(' ', u.student_id, j.scenario, j.last_error) ILIKE '%' || ${{search:sqlstring}} || '%')
ORDER BY j.updated_at DESC
LIMIT 100
""")], colored=["status"]), 24, 8)
L.add(table("Due but not sent", PG, [sql(f"""
SELECT j.id AS "id", COALESCE(u.student_id, j.user_id::text) AS "student", j.channel AS "channel",
       j.scenario AS "scenario", j.fire_at AS "fire at", j.available_at AS "available at",
       j.attempts || '/' || j.max_attempts AS "attempts", j.priority AS "priority",
       left(j.last_error, 200) AS "last error"
FROM push_jobs j
LEFT JOIN users u ON u.id = j.user_id
WHERE j.status = 'pending' AND j.fire_at <= now() AND j.available_at <= now() AND j.{CH}
ORDER BY j.fire_at
LIMIT 100
""")], from_now=["fire at"], desc="The jobs behind 'Due, not yet sent', most overdue first."), 24, 7)

push_vars = [
    var_custom("channel", "Channel", [(c, c) for c in ("assignment", "course", "bulletin", "system", "custom", "schedule")],
               "$__all", multi=True, include_all=True),
    var_custom("provider", "Provider", [("APNs", "apns"), ("FCM", "fcm")], "$__all", multi=True, include_all=True),
    var_text("search", "Search failures", "Student ID, scenario or error text"),
    var_prom_value("push_stale_lock", 'max(tigerduck_stale_lock_seconds{queue="push"})'),
]
dashboards["push-jobs"] = dashboard(
    "tigerduck-push-jobs", "Push", "The push_jobs queue, its deliveries, and the send path to APNs / FCM.",
    L.panels, "now-24h", push_vars)

# ======================================================================= Bulletins
SRC = "source IN (${source:sqlstring})"
L = Layout()
L.row("Now")
L.add(stat("Live bulletins", PG, [sql(f"SELECT count(*) AS \"bulletins\" FROM bulletins WHERE NOT is_deleted AND {SRC}")]), 3, 4)
L.add(stat("New in range", PG, [sql(f"SELECT count(*) AS \"new\" FROM bulletins WHERE $__timeFilter(first_seen_at) AND {SRC}")]), 3, 4)
L.add(stat("Waiting for the LLM", PG, [sql(f"SELECT count(*) AS \"pending\" FROM bulletins WHERE processing_state = 'pending' AND NOT is_deleted AND {SRC}")],
           thresholds=steps(("orange", 20), ("red", 100)),
           desc="Bulletins scraped but not yet classified. Grows when llama-server is down."), 3, 4)
L.add(stat("Processing failed", PG, [sql(f"SELECT count(*) AS \"failed\" FROM bulletins WHERE processing_state = 'failed' AND NOT is_deleted AND {SRC}")],
           thresholds=steps(("orange", 1))), 3, 4)
L.add(stat("Last scrape", PROM, [prom('time() - (max(tigerduck_scheduler_job_last_success_timestamp_seconds{job_id="bulletin_scrape"}) or max(process_start_time_seconds{job="backend"}))')], unit="s",
           thresholds=steps(("orange", 1800), ("red", 7200)), desc='Since the bulletin scraper last ran without an error. It runs every 10 minutes by default; right after a backend restart this counts from the restart until the first run.'), 3, 4)
L.add(stat("Subscriptions", PG, [sql("""
SELECT (SELECT count(*) FROM user_bulletin_subscriptions WHERE enabled AND deleted_at IS NULL)
     + (SELECT count(*) FROM bulletin_subscriptions WHERE enabled) AS "subscriptions"
""")], desc="Enabled subscriptions, signed-in and anonymous."), 3, 4)
L.add(stat("Matched in range", PG, [sql("SELECT count(*) AS \"matches\" FROM bulletin_user_matches WHERE $__timeFilter(matched_at)")]), 3, 4)
L.add(stat("Pushed in range", PG, [sql("SELECT count(*) AS \"pushed\" FROM bulletin_user_matches WHERE $__timeFilter(pushed_at)")]), 3, 4)

L.row("Over time")
L.add(series("New bulletins per day by unit", PG, [sql(per_day(f"""
SELECT {taipei_day("first_seen_at")} AS day, COALESCE(canonical_org, raw_publisher, 'unknown') AS metric, count(*) AS value
FROM bulletins
WHERE $__timeFilter(first_seen_at) AND {SRC}
GROUP BY 1, 2
""", by_metric=True), fmt="time_series")], bars=True, stacked=True, legend_table=True), 16, 9)
L.add(series("Processing state", PROM, [prom('sum by (processing_state) (tigerduck_bulletins)', "{{processing_state}}")],
             stacked=True, colors=True), 8, 9)
L.add(series("Matches and pushes per hour", PG, [sql("""
SELECT $__timeGroupAlias(matched_at, '1h', 0), count(*) AS "matched", count(pushed_at) AS "pushed"
FROM bulletin_user_matches
WHERE $__timeFilter(matched_at)
GROUP BY 1
ORDER BY 1
""", fmt="time_series")], bars=True), 12, 8)
L.add(series("LLM request time, p95", PROM, [prom(
    "histogram_quantile(0.95, sum by (le, outcome) (rate(tigerduck_llm_request_duration_seconds_bucket[$__rate_interval])))", "{{outcome}}")],
    unit="s", colors=True, desc="From the backend's own metrics: one classify request to llama-server."), 12, 8)

L.row("Details")
L.add(table("Recent bulletins", PG, [sql(f"""
SELECT first_seen_at AS "first seen", source AS "source", COALESCE(canonical_org, raw_publisher) AS "unit",
       COALESCE(title_clean, title) AS "title", importance AS "importance",
       array_to_string(content_tags, ', ') AS "tags", processing_state AS "state",
       processing_attempts AS "attempts", left(processing_error, 200) AS "error"
FROM bulletins
WHERE NOT is_deleted AND {SRC}
  AND (${{search:sqlstring}} = '' OR concat_ws(' ', title, title_clean, raw_publisher, canonical_org) ILIKE '%' || ${{search:sqlstring}} || '%')
ORDER BY first_seen_at DESC
LIMIT 300
""")], colored=["state"]), 24, 10)
L.add(bargauge("Processing errors", PG, [sql(f"""
SELECT left(COALESCE(processing_error, 'unknown'), 80) AS "error", count(*) AS "bulletins"
FROM bulletins
WHERE processing_state = 'failed' AND NOT is_deleted AND {SRC}
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
""")], values=True, thresholds=steps(base=RED)), 12, 8)
L.add(bargauge("Tags", PG, [sql(f"""
SELECT tag AS "tag", count(*) AS "bulletins"
FROM bulletins, unnest(content_tags) AS tag
WHERE NOT is_deleted AND $__timeFilter(first_seen_at) AND {SRC}
GROUP BY 1
ORDER BY 2 DESC
LIMIT 15
""")], values=True, desc="LLM-assigned tags on bulletins first seen in range."), 12, 8)

bulletin_vars = [
    var_sql("source", "Source", "SELECT DISTINCT source FROM bulletins ORDER BY 1"),
    var_text("search", "Search", "Title or unit"),
]
dashboards["bulletins"] = dashboard(
    "tigerduck-bulletins", "Bulletins", "Scrape → LLM classify → match → push.", L.panels, "now-7d", bulletin_vars)

# ======================================================================= Logs
SEL = '{service=~"$service"} | detected_level=~"$level" |~ `(?i)${search:regex}`'
L = Layout()
L.add(series("Log volume by level", LOKI, [loki(f"sum by (detected_level) (count_over_time({SEL} [$__auto]))", "{{detected_level}}")],
             bars=True, stacked=True, colors=True), 16, 7)
L.add(bargauge("Errors by service in range", LOKI, [loki(
    'sum by (service) (count_over_time({service=~"$service"} | detected_level=~"error|critical" [$__range]))', "{{service}}", instant=True)],
    thresholds=steps(("orange", 1), ("red", 50))), 8, 7)
L.add(logs("Logs", SEL, desc="Newest first. Click a line for its labels; the level comes from the line itself."), 24, 22)
log_vars = [
    var_loki_label("service", "Service", "service"),
    var_custom("level", "Level", [(lv, lv) for lv in ("critical", "error", "warn", "info", "debug", "unknown")],
               "$__all", multi=True, include_all=True, all_value=".*"),
    var_text("search", "Search", "Case-insensitive text match"),
]
dashboards["logs"] = dashboard(
    "tigerduck-logs", "Logs", "Every container in the stack, from Loki. 30 days of history.", L.panels, "now-1h",
    log_vars, refresh="30s")

# ======================================================================= Backend
R = 'route=~"$route"'
L = Layout()
L.row("Now")
L.add(stat("Version", PROM, [prom("tigerduck_build_info", "{{version}}", instant=True)], text_mode="name",
           thresholds=steps(base=BLUE)), 4, 4)
L.add(stat("Up", PROM, [prom('up{job="backend"}')],
           thresholds={"mode": "absolute", "steps": [{"color": "red", "value": None}, {"color": "green", "value": 1}]},
           mappings=[{"type": "value", "options": {"0": {"text": "DOWN"}, "1": {"text": "UP"}}}]), 3, 4)
L.add(stat("Requests / s", PROM, [prom(f"sum(rate(tigerduck_http_requests_total{{{R}}}[5m]))")], unit="reqps", graph=True, decimals=2), 4, 4)
L.add(stat("5xx share", PROM, [prom(f'sum(rate(tigerduck_http_requests_total{{{R}, status=~"5.."}}[5m])) / sum(rate(tigerduck_http_requests_total{{{R}}}[5m])) or vector(0)')],
           unit="percentunit", thresholds=steps(("orange", 0.01), ("red", 0.05)), graph=True), 4, 4)
L.add(stat("p95", PROM, [prom(f"histogram_quantile(0.95, sum by (le) (rate(tigerduck_http_request_duration_seconds_bucket{{{R}}}[5m])))")],
           unit="s", thresholds=steps(("orange", 1), ("red", 3)), graph=True, desc="95th percentile request time over the last 5 minutes."), 3, 4)
L.add(stat("In flight", PROM, [prom("tigerduck_http_requests_in_progress")], graph=True), 3, 4)
L.add(stat("Memory", PROM, [prom('process_resident_memory_bytes{job="backend"}')], unit="bytes", graph=True), 3, 4)

L.row("HTTP")
L.add(series("Requests / s by status", PROM, [prom(
    f'sum by (class) (label_replace(rate(tigerduck_http_requests_total{{{R}}}[$__rate_interval]), "class", "${{1}}xx", "status", "(\\\\d).."))', "{{class}}")],
    unit="reqps", stacked=True, colors=True), 12, 8)
L.add(series("Latency", PROM, [
    prom(f"histogram_quantile(0.5, sum by (le) (rate(tigerduck_http_request_duration_seconds_bucket{{{R}}}[$__rate_interval])))", "p50"),
    prom(f"histogram_quantile(0.95, sum by (le) (rate(tigerduck_http_request_duration_seconds_bucket{{{R}}}[$__rate_interval])))", "p95", ref="B"),
    prom(f"histogram_quantile(0.99, sum by (le) (rate(tigerduck_http_request_duration_seconds_bucket{{{R}}}[$__rate_interval])))", "p99", ref="C"),
], unit="s"), 12, 8)
L.add(table("Routes in range", PROM, [
    prom(f"sum by (method, route) (increase(tigerduck_http_requests_total{{{R}}}[$__range]))", instant=True, ref="A", table=True),
    prom(f'sum by (method, route) (increase(tigerduck_http_requests_total{{{R}, status=~"5.."}}[$__range]))', instant=True, ref="B", table=True),
    prom(f"histogram_quantile(0.95, sum by (le, method, route) (rate(tigerduck_http_request_duration_seconds_bucket{{{R}}}[$__range])))", instant=True, ref="C", table=True),
], units={"p95": "s"}, sort=("requests", True), widths={"method": 90},
    desc="Busiest routes in the time range, with their 5xx count and p95 latency. route=unmatched is everything that hit no route (404s, retired /v1 /v2)."), 24, 10)
L.panels[-1]["transformations"] = [
    {"id": "merge", "options": {}},
    {"id": "organize", "options": {"excludeByName": {"Time": True},
                                   "renameByName": {"Value #A": "requests", "Value #B": "5xx", "Value #C": "p95"}}},
]
L.add(series("Requests / s by route", PROM, [prom(
    f"topk(10, sum by (route) (rate(tigerduck_http_requests_total{{{R}}}[$__rate_interval])))", "{{route}}")],
    unit="reqps", legend_table=True), 24, 9)

L.row("Scheduler")
L.add(series("Job runs / min", PROM, [prom(
    "sum by (job_id) (rate(tigerduck_scheduler_job_runs_total[$__rate_interval])) * 60", "{{job_id}}")],
    unit="short", legend_table=True), 12, 9)
L.add(series("Job duration, p95", PROM, [prom(
    "histogram_quantile(0.95, sum by (le, job_id) (rate(tigerduck_scheduler_job_duration_seconds_bucket[$__rate_interval])))", "{{job_id}}")],
    unit="s", legend_table=True), 12, 9)
L.add(stat("Errors, skipped and missed runs in range", PROM, [prom(
    'sum by (outcome) (increase(tigerduck_scheduler_job_runs_total{outcome!="success"}[$__range]))', "{{outcome}}", instant=True)],
    text_mode="value_and_name", thresholds=steps(("orange", 1)),
    desc="skipped: a run was due while the previous one was still going (max_instances). missed: the scheduler woke up too late."), 8, 8)
L.add(series("Runs that didn't succeed", PROM, [prom(
    'sum by (job_id, outcome) (increase(tigerduck_scheduler_job_runs_total{outcome!="success"}[$__rate_interval])) > 0', "{{job_id}} {{outcome}}")],
    bars=True, stacked=True, regex_colors=True, desc="Empty is good."), 16, 8)

L.row("Database pool and process")
L.add(series("SQLAlchemy pool", PROM, [
    prom('tigerduck_db_pool_connections{state="checked_out"}', "checked out"),
    prom('tigerduck_db_pool_connections{state="overflow"}', "overflow", ref="B"),
    prom("tigerduck_db_pool_size + tigerduck_db_pool_max_overflow", "limit", ref="C"),
], desc="Connections the backend holds from its pool. Checked out reaching the limit means requests queue for a connection."), 8, 8)
L.add(series("CPU", PROM, [prom('rate(process_cpu_seconds_total{job="backend"}[$__rate_interval])', "cpu")], unit="percentunit"), 8, 8)
L.add(series("Memory", PROM, [prom('process_resident_memory_bytes{job="backend"}', "resident")], unit="bytes"), 8, 8)

backend_vars = [var_prom("route", "Route", "label_values(tigerduck_http_requests_total, route)")]
dashboards["backend"] = dashboard(
    "tigerduck-backend", "Backend API", "The FastAPI process: HTTP traffic, scheduler jobs, DB pool, CPU and memory.",
    L.panels, "now-6h", backend_vars)

# ======================================================================= Postgres
L = Layout()
L.row("Overview")
L.add(stat("Postgres", PROM, [prom("pg_up", instant=True)],
           desc="Whether postgres-exporter could connect on its last scrape.",
           thresholds={"mode": "absolute", "steps": [{"color": "red", "value": None}, {"color": "green", "value": 1}]},
           mappings=[{"type": "value", "options": {"0": {"text": "DOWN"}, "1": {"text": "UP"}}}]), 4, 4)
L.add(stat("Connections", PROM, [prom("sum(pg_stat_activity_count)")],
           desc="Client sessions open on the server, every database and role.", graph=True), 4, 4)
L.add(stat("Of max_connections", PROM, [prom("sum(pg_stat_activity_count) / max(pg_settings_max_connections)")],
           unit="percentunit", thresholds=steps(("orange", 0.7), ("red", 0.9)),
           desc="Open sessions as a share of max_connections. The backend pool alone can hold 10."), 4, 4)
L.add(stat("Longest open transaction", PROM, [prom(f"max(pg_stat_activity_max_tx_duration{{{DB}}})")],
           unit="s", thresholds=steps(("orange", 60), ("red", 300)),
           desc="Age of the oldest transaction still open. A long one that is idle in transaction usually means a session that never committed or rolled back."), 4, 4)
L.add(stat("Database size", PROM, [prom(f"pg_database_size_bytes{{{DB}}}")], unit="bytes", graph=True), 4, 4)
L.add(stat("Deadlocks (24h)", PROM, [prom(f"increase(pg_stat_database_deadlocks{{{DB}}}[24h])", instant=True)],
           thresholds=steps(("red", 1))), 4, 4)

L.row("Connections")
L.add(series("Connections by state", PROM,
             [prom(f'sum by (state) (pg_stat_activity_count{{{DB}, state=~"active|idle|idle in transaction.*"}})', "{{state}}")],
             stacked=True, desc="Sessions on the tigerduck database. 'idle in transaction' that stays up is a leaked session."), 12, 8)
L.add(series("Longest transaction by state", PROM,
             [prom(f'pg_stat_activity_max_tx_duration{{{DB}, state=~"active|idle in transaction.*"}}', "{{state}}")],
             unit="s"), 12, 8)
L.add(table("Sessions by client", PG, [sql("""
SELECT usename AS "role",
       COALESCE(NULLIF(application_name, ''), '-') AS "application",
       COALESCE(client_addr::text, 'local') AS "client",
       count(*) AS "total",
       count(*) FILTER (WHERE state = 'active') AS "active",
       count(*) FILTER (WHERE state = 'idle') AS "idle",
       count(*) FILTER (WHERE state LIKE 'idle in transaction%') AS "idle in tx"
FROM pg_stat_activity
WHERE datname = 'tigerduck'
GROUP BY 1, 2, 3
ORDER BY "total" DESC
""")], desc="Who holds connections right now. The backend and portal both log in as tigerduck; tell them apart by client address. tigerduck_monitor is Grafana and the exporters."), 24, 6)
L.add(table("Live sessions", PG, [sql("""
SELECT pid,
       usename AS "role",
       COALESCE(client_addr::text, 'local') AS "client",
       state,
       wait_event_type || ': ' || wait_event AS "waiting on",
       round(extract(epoch FROM now() - xact_start))::int AS "in transaction",
       round(extract(epoch FROM now() - query_start))::int AS "since last query",
       left(query, 300) AS "last query"
FROM pg_stat_activity
WHERE datname = 'tigerduck' AND pid <> pg_backend_pid()
ORDER BY xact_start NULLS LAST, query_start
""")], units={"in transaction": "s", "since last query": "s"},
            desc="Every session on the tigerduck database, oldest transaction first. Snapshot at refresh time."), 24, 7)

L.row("Activity")
L.add(series("Transactions / s", PROM, [
    prom(f"rate(pg_stat_database_xact_commit{{{DB}}}[$__rate_interval])", "commit"),
    prom(f"rate(pg_stat_database_xact_rollback{{{DB}}}[$__rate_interval])", "rollback", ref="B"),
], unit="ops"), 8, 8)
L.add(series("Rows / s", PROM, [
    prom(f"rate(pg_stat_database_tup_inserted{{{DB}}}[$__rate_interval])", "inserted"),
    prom(f"rate(pg_stat_database_tup_updated{{{DB}}}[$__rate_interval])", "updated", ref="B"),
    prom(f"rate(pg_stat_database_tup_deleted{{{DB}}}[$__rate_interval])", "deleted", ref="C"),
    prom(f"rate(pg_stat_database_tup_fetched{{{DB}}}[$__rate_interval])", "fetched", ref="D"),
], unit="ops"), 8, 8)
L.add(series("Locks by mode", PROM,
             [prom(f"sum by (mode) (pg_locks_count{{{DB}}}) > 0", "{{mode}}")], stacked=True), 8, 8)
L.add(series("Cache hit ratio", PROM, [prom(
    f"sum(rate(pg_stat_database_blks_hit{{{DB}}}[$__rate_interval])) / "
    f"(sum(rate(pg_stat_database_blks_hit{{{DB}}}[$__rate_interval])) + sum(rate(pg_stat_database_blks_read{{{DB}}}[$__rate_interval])))",
    "hit ratio")], unit="percentunit", min0=False,
    desc="Share of block reads served from shared buffers. Gaps mean nothing was read."), 8, 8)
L.add(bargauge("Largest tables", PROM, [prom(
    f"topk(10, pg_stat_user_tables_table_size_bytes{{{DB}}} + pg_stat_user_tables_index_size_bytes{{{DB}}})",
    "{{relname}}", instant=True)], "bytes", desc="Table plus index size."), 8, 8)
L.add(bargauge("Dead rows", PROM, [prom(
    f"topk(10, pg_stat_user_tables_n_dead_tup{{{DB}}} > 0)", "{{relname}}", instant=True)], "short",
    desc="Rows waiting for vacuum. A table that keeps growing here isn't being vacuumed often enough. Empty is good."), 8, 8)
dashboards["postgres"] = dashboard(
    "tigerduck-postgres", "Postgres", "Server health for tigerduck-db: connections, transactions, locks and sizes.",
    L.panels, "now-6h")


# ======================================================================= Userbase
DASH_DS = {"type": "datasource", "uid": "-- Dashboard --"}
PLATFORM_COLORS = {"iPhone \\+ iPad": "blue", "macOS": "purple", "Android": "green"}
PLATFORM_GROUP = """CASE WHEN {col} IN ('ios', 'ipados') THEN '{a}'
                WHEN {col} = 'macos' THEN '{b}'
                WHEN {col} = 'android' THEN '{c}'
                ELSE 'other' END"""


def stretches(name):
    """Merges each key's activity into active stretches: every moment of
    activity keeps the key active for 14 days, and overlapping 14-day spans
    join up, so at any time a key sits inside at most one stretch and
    counting stretches counts keys. {name}_daily has one row per key per day
    with that day's first and last moment, so the edges stay exact."""
    return f"""{name}_marked AS (
    SELECT key, day, first_at, last_at,
           CASE WHEN lag(last_at) OVER w + interval '14 days' >= first_at THEN 0 ELSE 1 END AS starts_new
    FROM {name}_daily
    WINDOW w AS (PARTITION BY key ORDER BY day)
),
{name}_numbered AS (
    SELECT key, first_at, last_at, sum(starts_new) OVER (PARTITION BY key ORDER BY day) AS stretch
    FROM {name}_marked
),
{name}_spans AS (
    SELECT key, min(first_at) AS active_from, max(last_at) + interval '14 days' AS active_until
    FROM {name}_numbered
    GROUP BY key, stretch
)"""


# One query feeds the whole top of the dashboard (both graphs and every big
# number), so auth_sessions is scanned once per refresh rather than once per
# panel. Every other panel there reads its result through the Dashboard
# datasource.
USERBASE_SQL = f"""WITH points AS (
    -- Sample times across the range, plus now() so the last point is the
    -- current number.
    SELECT generate_series(
               date_trunc('hour', $__timeFrom()::timestamptz),
               now(),
               GREATEST(make_interval(secs => $__interval_ms / 1000.0), interval '1 hour')
           ) AS t
    UNION
    SELECT now()
),
seen AS (
    -- Activity: logins and access-token refreshes (auth_sessions keeps every
    -- one, and an app in use refreshes every 15 minutes), plus each
    -- device's latest request.
    SELECT device_id, created_at AS at
    FROM auth_sessions
    WHERE device_id IS NOT NULL
      AND created_at > $__timeFrom()::timestamptz - interval '14 days'
    UNION ALL
    SELECT id, last_seen_at
    FROM user_devices
    WHERE last_seen_at > $__timeFrom()::timestamptz - interval '14 days'
),
dev AS (
    SELECT d.id, d.created_at, d.deleted_at, u.student_id,
           {PLATFORM_GROUP.format(col="d.platform", a="iphone_ipad", b="macos", c="android")} AS grp
    FROM user_devices d
    JOIN users u ON u.id = d.user_id
),
device_daily AS (
    SELECT device_id AS key, date_trunc('day', at) AS day, min(at) AS first_at, max(at) AS last_at
    FROM seen
    GROUP BY 1, 2
),
student_daily AS (
    SELECT dv.student_id AS key, dd.day, min(dd.first_at) AS first_at, max(dd.last_at) AS last_at
    FROM device_daily dd
    JOIN dev dv ON dv.id = dd.key
    WHERE dv.student_id IS NOT NULL
    GROUP BY 1, 2
),
{stretches("device")},
{stretches("student")}
SELECT p.t AS "time", usr.*, reg.*, act.*,
       usr."Active users, 14 days"::float / NULLIF(usr."Registered users", 0) AS "Active share"
FROM points p
CROSS JOIN LATERAL (
    SELECT (SELECT count(DISTINCT u.student_id)
            FROM users u
            WHERE u.student_id IS NOT NULL
              AND u.created_at <= p.t
              AND (u.deleted_at IS NULL OR u.deleted_at > p.t)) AS "Registered users",
           (SELECT count(*)
            FROM student_spans s
            WHERE s.active_from <= p.t AND s.active_until > p.t
              -- Counted like "Registered users": not before the account
              -- existed, nor after it was deleted.
              AND EXISTS (SELECT 1
                          FROM users u
                          WHERE u.student_id = s.key
                            AND u.created_at <= p.t
                            AND (u.deleted_at IS NULL OR u.deleted_at > p.t))) AS "Active users, 14 days"
) AS usr
CROSS JOIN LATERAL (
    SELECT count(*) FILTER (WHERE grp = 'iphone_ipad') AS "Registered: iPhone + iPad",
           count(*) FILTER (WHERE grp = 'macos') AS "Registered: macOS",
           count(*) FILTER (WHERE grp = 'android') AS "Registered: Android",
           count(*) AS "Registered: all"
    FROM dev
    WHERE created_at <= p.t AND (deleted_at IS NULL OR deleted_at > p.t)
) AS reg
CROSS JOIN LATERAL (
    SELECT count(*) FILTER (WHERE dv.grp = 'iphone_ipad') AS "Active 14d: iPhone + iPad",
           count(*) FILTER (WHERE dv.grp = 'macos') AS "Active 14d: macOS",
           count(*) FILTER (WHERE dv.grp = 'android') AS "Active 14d: Android",
           count(*) AS "Active 14d: all"
    FROM device_spans s
    JOIN dev dv ON dv.id = s.key
    WHERE s.active_from <= p.t AND s.active_until > p.t
      -- A deleted device stops counting as active, as it stops counting
      -- as registered.
      AND (dv.deleted_at IS NULL OR dv.deleted_at > p.t)
) AS act
ORDER BY 1"""


def from_panel(title, panel_id, field, color, desc="", unit="short", decimals=None):
    """A big number taken from another panel's query: its latest value."""
    p = stat(title, DASH_DS, [{"refId": "A", "datasource": DASH_DS, "panelId": panel_id, "withTransforms": False}],
             thresholds=steps(base=color), desc=desc, graph=True, unit=unit, decimals=decimals)
    p["options"]["reduceOptions"]["fields"] = f"/^{field}$/"
    return p


def without_fields(pattern):
    """Drops the fields matching `pattern`. Excluding rather than including
    keeps the time field, whatever name Grafana gives it."""
    return [{"id": "filterFieldsByName", "options": {"exclude": {"pattern": pattern}}}]


def line_styles(colors):
    out = []
    for name, color in colors.items():
        out.append({"matcher": {"id": "byRegexp", "options": f".*{name}$"},
                    "properties": [{"id": "color", "value": {"mode": "fixed", "fixedColor": color}}]})
    out.append({"matcher": {"id": "byRegexp", "options": "^Active.*"},
                "properties": [{"id": "custom.lineStyle", "value": {"fill": "dash", "dash": [10, 10]}},
                               {"id": "custom.fillOpacity", "value": 0}]})
    out.append({"matcher": {"id": "byRegexp", "options": ".*: all$"},
                "properties": [{"id": "custom.hideFrom", "value": {"viz": True, "legend": True, "tooltip": False}}]})
    return out


def wide_graph(panel):
    panel["fieldConfig"]["defaults"]["custom"]["lineWidth"] = 2
    panel["options"]["legend"].update({"calcs": ["lastNotNull"], "displayMode": "table", "placement": "right"})
    return panel


ACTIVE_DESC = ("A device is active for 14 days after any login, token refresh or request. Apps in use refresh "
               "their token every 15 minutes, and every refresh is kept, so the history reaches back to launch.")

L = Layout()
L.row("Users")
source = L.reserve()  # the Users graph, which runs USERBASE_SQL
L.add(from_panel("Registered users", source, "Registered users", "blue",
                 desc="Distinct student IDs signed in at least once, not deleted."), 6, 5)
L.add(from_panel("Active users, 14 days", source, "Active users, 14 days", "green",
                 desc="Students with at least one device active in the last 14 days. " + ACTIVE_DESC), 6, 5)
L.add(stat("New users in range", PG, [sql("""
SELECT count(DISTINCT student_id) AS "new"
FROM users
WHERE student_id IS NOT NULL AND deleted_at IS NULL AND $__timeFilter(created_at)
""")], thresholds=steps(base="blue"), desc="Students whose first sign-in falls in the selected time range."), 6, 5)
L.add(from_panel("Active share", source, "Active share", "green", unit="percentunit", decimals=0,
                 desc="Active users over registered users, both as in the Users graph below."), 6, 5)
users_panel = wide_graph(series("Users", PG, [sql(USERBASE_SQL, fmt="time_series")], decimals=0,
                                desc="Registered: distinct student IDs. Active (dashed): students with a device active in the trailing 14 days. " + ACTIVE_DESC))
users_panel["fieldConfig"]["overrides"] = [
    {"matcher": {"id": "byName", "options": "Registered users"},
     "properties": [{"id": "color", "value": {"mode": "fixed", "fixedColor": "blue"}}]},
    {"matcher": {"id": "byName", "options": "Active users, 14 days"},
     "properties": [{"id": "color", "value": {"mode": "fixed", "fixedColor": "green"}},
                    {"id": "custom.lineStyle", "value": {"fill": "dash", "dash": [10, 10]}},
                    {"id": "custom.fillOpacity", "value": 0}]},
]
users_panel["maxDataPoints"] = 200
users_panel["transformations"] = without_fields("^((Registered|Active 14d): .*|Active share)$")
L.add(users_panel, 24, 10, pid=source)

L.row("Devices")
for group, color in (("iPhone \\+ iPad", "blue"), ("macOS", "purple"), ("Android", "green"), ("all", "text")):
    L.add(from_panel(f"Registered: {group.replace(chr(92), '')}", source, f"Registered: {group}", color,
                     desc="Registered devices, not deleted."), 6, 4)
for group, color in (("iPhone \\+ iPad", "blue"), ("macOS", "purple"), ("Android", "green"), ("all", "text")):
    L.add(from_panel(f"Active 14d: {group.replace(chr(92), '')}", source, f"Active 14d: {group}", color,
                     desc="Devices active in the last 14 days. " + ACTIVE_DESC), 6, 4)
devices_panel = wide_graph(series(
    "Devices", DASH_DS, [{"refId": "A", "datasource": DASH_DS, "panelId": source, "withTransforms": False}],
    decimals=0,
    desc="Solid: registered devices. Dashed: devices active in the trailing 14 days. Same colour, same platform. Hover for the totals. " + ACTIVE_DESC))
devices_panel["fieldConfig"]["overrides"] = line_styles(PLATFORM_COLORS)
devices_panel["fieldConfig"]["defaults"]["custom"]["fillOpacity"] = 0
devices_panel["transformations"] = without_fields("^(Registered users|Active users, 14 days|Active share)$")
L.add(devices_panel, 24, 12)

L.row("Growth")
new_users = series("New users per day", PG, [sql(per_day(f"""
SELECT {taipei_day("created_at")} AS day, count(DISTINCT student_id) AS value
FROM users
WHERE student_id IS NOT NULL AND $__timeFilter(created_at)
GROUP BY 1
""", by_metric=False), fmt="time_series")], bars=True, decimals=0)
new_users["fieldConfig"]["defaults"]["displayName"] = "new users"
L.add(new_users, 12, 8)
new_devices = series("New devices per day", PG, [sql(per_day(f"""
SELECT {taipei_day("created_at")} AS day,
       {PLATFORM_GROUP.format(col="platform", a="iPhone + iPad", b="macOS", c="Android")} AS metric,
       count(*) AS value
FROM user_devices
WHERE $__timeFilter(created_at)
GROUP BY 1, 2
""", by_metric=True), fmt="time_series")], bars=True, stacked=True, decimals=0)
new_devices["fieldConfig"]["overrides"] = [
    {"matcher": {"id": "byName", "options": n},
     "properties": [{"id": "color", "value": {"mode": "fixed", "fixedColor": c}}]}
    for n, c in (("iPhone + iPad", "blue"), ("macOS", "purple"), ("Android", "green"), ("other", GRAY))]
L.add(new_devices, 12, 8)

dashboards["userbase"] = dashboard(
    "tigerduck-userbase", "Userbase",
    "Registered and active users and devices over time. Rebuilt from the database, so the history reaches back to launch.",
    L.panels, "now-90d", refresh="5m")

# ----------------------------------------------------------------- write
for name, d in dashboards.items():
    (OUT / f"{name}.json").write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")
    print(f"{name}.json: {sum(1 for p in d['panels'] if p['type'] != 'row')} panels, "
          f"{len(d['templating']['list'])} variables")
