"""create device_registrations and scheduled_pushes

Revision ID: 82ca260175e4
Revises: 
Create Date: 2026-04-22 06:11:31.224838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82ca260175e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_registrations',
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('pts_token_hex', sa.String(length=512), nullable=False),
    sa.Column('device_token_hex', sa.String(length=512), nullable=True),
    sa.Column('bundle_id', sa.String(length=128), nullable=False),
    sa.Column('attrs_type', sa.String(length=128), nullable=False),
    sa.Column('apns_env', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_device_registrations_user_id'), 'device_registrations', ['user_id'], unique=False)
    op.create_table('scheduled_pushes',
    sa.Column('push_id', sa.String(length=256), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.BigInteger(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device_registrations.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('push_id')
    )
    op.create_index('ix_pushes_due', 'scheduled_pushes', ['status', 'fire_at'], unique=False)
    op.create_index(op.f('ix_scheduled_pushes_device_id'), 'scheduled_pushes', ['device_id'], unique=False)
    op.create_index(op.f('ix_scheduled_pushes_fire_at'), 'scheduled_pushes', ['fire_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_pushes_fire_at'), table_name='scheduled_pushes')
    op.drop_index(op.f('ix_scheduled_pushes_device_id'), table_name='scheduled_pushes')
    op.drop_index('ix_pushes_due', table_name='scheduled_pushes')
    op.drop_table('scheduled_pushes')
    op.drop_index(op.f('ix_device_registrations_user_id'), table_name='device_registrations')
    op.drop_table('device_registrations')
    # ### end Alembic commands ###
