"""create bulletins tables

Revision ID: 8ef231bb5a0c
Revises: 82ca260175e4
Create Date: 2026-04-22 08:42:43.614952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ef231bb5a0c'
down_revision: Union[str, Sequence[str], None] = '82ca260175e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletins',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('raw_publisher', sa.String(length=128), nullable=True),
    sa.Column('canonical_org', sa.String(length=32), nullable=True),
    sa.Column('content_tags', postgresql.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body_clean', sa.Text(), nullable=True),
    sa.Column('importance', sa.String(length=16), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('processing_state', sa.String(length=16), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processing_attempts', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_bulletins_source_extid')
    )
    op.create_index('ix_bulletins_content_hash', 'bulletins', ['source', 'content_hash'], unique=True, postgresql_where=sa.text('content_hash IS NOT NULL'))
    op.create_index('ix_bulletins_notify_queue', 'bulletins', ['processing_state', 'notified_at'], unique=False, postgresql_where=sa.text('notified_at IS NULL'))
    op.create_index('ix_bulletins_pending', 'bulletins', ['processing_state'], unique=False, postgresql_where=sa.text("processing_state = 'pending'"))
    op.create_table('bulletin_dispatches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bulletin_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['device_registrations.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bulletin_id', 'device_id', name='uq_dispatch_bulletin_device')
    )
    op.create_index(op.f('ix_bulletin_dispatches_bulletin_id'), 'bulletin_dispatches', ['bulletin_id'], unique=False)
    op.create_index(op.f('ix_bulletin_dispatches_device_id'), 'bulletin_dispatches', ['device_id'], unique=False)
    op.create_index('ix_dispatches_due', 'bulletin_dispatches', ['status'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('bulletin_subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('orgs', postgresql.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('mode', sa.String(length=4), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('AND','OR')", name='ck_subs_mode'),
    sa.ForeignKeyConstraint(['device_id'], ['device_registrations.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulletin_subscriptions_device_id'), 'bulletin_subscriptions', ['device_id'], unique=False)
    op.create_index('ix_subs_enabled_device', 'bulletin_subscriptions', ['device_id'], unique=False, postgresql_where=sa.text('enabled IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subs_enabled_device', table_name='bulletin_subscriptions', postgresql_where=sa.text('enabled IS true'))
    op.drop_index(op.f('ix_bulletin_subscriptions_device_id'), table_name='bulletin_subscriptions')
    op.drop_table('bulletin_subscriptions')
    op.drop_index('ix_dispatches_due', table_name='bulletin_dispatches', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_bulletin_dispatches_device_id'), table_name='bulletin_dispatches')
    op.drop_index(op.f('ix_bulletin_dispatches_bulletin_id'), table_name='bulletin_dispatches')
    op.drop_table('bulletin_dispatches')
    op.drop_index('ix_bulletins_pending', table_name='bulletins', postgresql_where=sa.text("processing_state = 'pending'"))
    op.drop_index('ix_bulletins_notify_queue', table_name='bulletins', postgresql_where=sa.text('notified_at IS NULL'))
    op.drop_index('ix_bulletins_content_hash', table_name='bulletins', postgresql_where=sa.text('content_hash IS NOT NULL'))
    op.drop_table('bulletins')
    # ### end Alembic commands ###
