"""phase4c linked user marker and bulletin match runs

Revision ID: db27e6d1b65a
Revises: e0f7f827758f
Create Date: 2026-06-10 15:29:17.770728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db27e6d1b65a'
down_revision: Union[str, Sequence[str], None] = 'e0f7f827758f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletin_user_match_runs',
    sa.Column('bulletin_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bulletin_id')
    )
    op.add_column('device_registrations', sa.Column('linked_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_device_registrations_linked_user',
        'device_registrations', 'users',
        ['linked_user_id'], ['id'], ondelete='SET NULL',
    )
    # Backfill: devices already registered by a logged-in v3 user_device
    # (matched on client_device_id) start out linked, so the anonymous
    # bulletin fan-out stops double-pushing to them immediately.
    op.execute(
        """
        UPDATE device_registrations dr
        SET linked_user_id = ud.user_id
        FROM user_devices ud
        WHERE ud.client_device_id = dr.device_id
          AND ud.deleted_at IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_device_registrations_linked_user',
        'device_registrations',
        type_='foreignkey',
    )
    op.drop_column('device_registrations', 'linked_user_id')
    op.drop_table('bulletin_user_match_runs')
    # ### end Alembic commands ###
