"""phase3 sync jobs

Revision ID: e0f7f827758f
Revises: b8d4f0a2c3e9
Create Date: 2026-06-10 07:08:40.293437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0f7f827758f'
down_revision: Union[str, Sequence[str], None] = 'b8d4f0a2c3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_policies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('default_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('ntust_courses', 'moodle_assignments', 'calendar', 'grades')", name='chk_sync_policy_job_type'),
    sa.CheckConstraint('default_interval_seconds > 0', name='chk_sync_policy_interval'),
    sa.CheckConstraint('max_attempts > 0', name='chk_sync_policy_attempts'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_type')
    )
    op.create_table('sync_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('external_account_id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('ntust_courses', 'moodle_assignments', 'calendar', 'grades')", name='chk_sync_job_type'),
    sa.CheckConstraint("status IN ('pending', 'running', 'failed', 'disabled')", name='chk_sync_job_status'),
    sa.CheckConstraint('attempts >= 0 AND max_attempts > 0', name='chk_sync_job_attempts'),
    sa.ForeignKeyConstraint(['external_account_id'], ['external_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_type')
    )
    op.create_index('idx_sync_jobs_due', 'sync_jobs', ['status', 'run_after', 'priority'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('sync_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sync_job_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=True),
    sa.Column('changed_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'cancelled')", name='chk_sync_run_status'),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_runs_job', 'sync_runs', ['sync_job_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('idx_sync_runs_user_recent', 'sync_runs', ['user_id', sa.literal_column('started_at DESC')], unique=False)
    # ### end Alembic commands ###
    op.execute(
        """
        INSERT INTO sync_policies (job_type, enabled, default_interval_seconds)
        VALUES
            ('moodle_assignments', true, 28800),
            ('ntust_courses', false, 28800),
            ('calendar', true, 604800),
            ('grades', false, 28800)
        ON CONFLICT (job_type) DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sync_runs_user_recent', table_name='sync_runs')
    op.drop_index('idx_sync_runs_job', table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index('idx_sync_jobs_due', table_name='sync_jobs', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('sync_jobs')
    op.drop_table('sync_policies')
    # ### end Alembic commands ###
