"""device_uuid_v2_sunset

Revision ID: f7e3a6d9c2b1
Revises: db27e6d1b65a
Create Date: 2026-06-18 04:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e3a6d9c2b1'
down_revision: Union[str, Sequence[str], None] = 'db27e6d1b65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_devices",
        sa.Column(
            "server_push_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.drop_constraint("chk_push_job_channel", "push_jobs", type_="check")
    op.create_check_constraint(
        "chk_push_job_channel",
        "push_jobs",
        "channel IN ('assignment', 'course', 'bulletin', 'system', 'custom', 'schedule')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chk_push_job_channel", "push_jobs", type_="check")
    op.create_check_constraint(
        "chk_push_job_channel",
        "push_jobs",
        "channel IN ('assignment', 'course', 'bulletin', 'system', 'custom')",
    )
    op.drop_column("user_devices", "server_push_enabled")
    # ### end Alembic commands ###
